# Generated by Django 4.2.7 on 2024-09-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_location_delete_park'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='points',
            new_name='point',
        ),
    ]
